// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ckxKDEnVLEc-raTbIm4_9GODpdoLlgA',
    appId: '1:256716519580:web:4797e232e637beb80c1559',
    messagingSenderId: '256716519580',
    projectId: 'student-app-801d2',
    authDomain: 'student-app-801d2.firebaseapp.com',
    storageBucket: 'student-app-801d2.firebasestorage.app',
    measurementId: 'G-R1BMDT1TGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIDmpN28Bb5GXpkiaiib5EKD1PappLxEc',
    appId: '1:256716519580:android:66f22af140a0bc560c1559',
    messagingSenderId: '256716519580',
    projectId: 'student-app-801d2',
    storageBucket: 'student-app-801d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNpkT6flktSX8qr-9TqUMg9gqAlKusUo',
    appId: '1:256716519580:ios:d2e9f1ee625d61f10c1559',
    messagingSenderId: '256716519580',
    projectId: 'student-app-801d2',
    storageBucket: 'student-app-801d2.firebasestorage.app',
    iosBundleId: 'com.example.studentInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNpkT6flktSX8qr-9TqUMg9gqAlKusUo',
    appId: '1:256716519580:ios:d2e9f1ee625d61f10c1559',
    messagingSenderId: '256716519580',
    projectId: 'student-app-801d2',
    storageBucket: 'student-app-801d2.firebasestorage.app',
    iosBundleId: 'com.example.studentInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ckxKDEnVLEc-raTbIm4_9GODpdoLlgA',
    appId: '1:256716519580:web:e56a7fce7c2ff2f30c1559',
    messagingSenderId: '256716519580',
    projectId: 'student-app-801d2',
    authDomain: 'student-app-801d2.firebaseapp.com',
    storageBucket: 'student-app-801d2.firebasestorage.app',
    measurementId: 'G-8YEWVE4G1E',
  );
}
