// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXqvNYN8_fW8bQds-nqi8yEwIqQzvSKj8',
    appId: '1:825013653940:web:9064ff433af806e18f62e1',
    messagingSenderId: '825013653940',
    projectId: 'exile1-c1887',
    authDomain: 'exile1-c1887.firebaseapp.com',
    storageBucket: 'exile1-c1887.firebasestorage.app',
    measurementId: 'G-CZPLYTRE0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDht_hE027Deup5uSXAKtuXxQ8Mj7-z_lA',
    appId: '1:825013653940:android:68a1b976aa4933908f62e1',
    messagingSenderId: '825013653940',
    projectId: 'exile1-c1887',
    storageBucket: 'exile1-c1887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmylaBDlFTw6jm1GysBU9F4yE_KyCPO7I',
    appId: '1:825013653940:ios:9b8b884413c88b4b8f62e1',
    messagingSenderId: '825013653940',
    projectId: 'exile1-c1887',
    storageBucket: 'exile1-c1887.firebasestorage.app',
    iosBundleId: 'com.marwan.exsail5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmylaBDlFTw6jm1GysBU9F4yE_KyCPO7I',
    appId: '1:825013653940:ios:9b8b884413c88b4b8f62e1',
    messagingSenderId: '825013653940',
    projectId: 'exile1-c1887',
    storageBucket: 'exile1-c1887.firebasestorage.app',
    iosBundleId: 'com.marwan.exsail5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXqvNYN8_fW8bQds-nqi8yEwIqQzvSKj8',
    appId: '1:825013653940:web:bdfa3d24e8d8112c8f62e1',
    messagingSenderId: '825013653940',
    projectId: 'exile1-c1887',
    authDomain: 'exile1-c1887.firebaseapp.com',
    storageBucket: 'exile1-c1887.firebasestorage.app',
    measurementId: 'G-BX9PY25ZWH',
  );
}
